---
title: "Exercise 3"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r 3data}
resume <- 
  here::here("data", "resume_HW.csv") %>% 
  read_csv() %>% 
  janitor::clean_names() %>% 
  rename(years_exp = yearsexp,
         computer_skills = computerskills)
```

### (a)

### (b)

```{r 3b}
resume %>% 
  lm(cbind(education, years_exp, honors, 
           volunteer, computer_skills, female) ~ afn_american,
     .) %>% 
  broom::tidy() %>% 
  filter(term == "afn_american") %>% 
  select(response, statistic, p.value) 
```

### (c)

### (d)

### (e)

```{r 3e}
resume %>% 
  lm(call ~ afn_american, .) %>% 
  jtools::summ()
```

### (f)

### (g)

```{r 3g}
resume %>% 
  lm(call ~ afn_american + 
       education + years_exp + honors + volunteer + computer_skills + female,
     data = .) %>% 
  jtools::summ()
```

### (h)

```{r 3h}
resume %>% 
  lm(call ~ afn_american * h_quality + 
       education + years_exp + honors + volunteer + computer_skills + female,
     data = .) %>% 
  jtools::summ()
```

