---
title: "Exercise 4"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, 
                      message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r 4data}
schools <- 
  here::here("data", "schools_experiment_HW.csv") %>% 
  read_csv() %>% 
  janitor::clean_names() %>% 
  rename(cluster_code = clustercode,
         test_scores = testscores)
```

### (a)

### (b)

### (c)

```{r 4c}
schools %>% 
  lm(cbind(age, girl, sheep, duration_village, farmer, 
           education_head, number_ppl_hh, distance_nearest_school) ~ 
       treatment, .) %>% 
  broom::tidy() %>% 
  filter(term == "treatment") %>% 
  select(response, statistic, p.value) 
```


### (d)

```{r 4d}
schools %>% 
  lm(cbind(age, girl, sheep, duration_village, farmer, education_head, 
           number_ppl_hh, distance_nearest_school) ~ treatment, .) %>% 
    clubSandwich::coef_test(vcov = "CR1", cluster = schools$cluster_code) %>% 
  rownames_to_column("coef") %>% 
  as_tibble() %>% 
  filter(str_detect(coef, "treatment"))
```

### (e)

```{r 4e}
schools %>% 
  lm(formal_school ~ treatment, .) %>% 
  jtools::summ(digits = 4)

schools %>% 
  lm(formal_school ~ treatment, .) %>% 
  broom::augment() %>% 
  distinct(.fitted)

# clustered errors

schools %>% 
  lm(formal_school ~ treatment, .) %>% 
  clubSandwich::coef_test(vcov = "CR1", cluster = schools$cluster_code) 

```


### (f)

```{r 4f}
schools %>% 
  lm(formal_school ~ treatment + age + girl + sheep + duration_village + 
       farmer + education_head + number_ppl_hh + distance_nearest_school, .) %>% 
  jtools::summ(digits = 4)

# clustered errors

schools %>% 
  lm(formal_school ~ treatment + age + girl + sheep + duration_village + 
       farmer + education_head + number_ppl_hh + distance_nearest_school, .) %>%
  clubSandwich::coef_test(vcov = "CR1", cluster = schools$cluster_code)

```

### (g)

```{r 4g}
schools %>% 
  lm(test_scores ~ treatment, .) %>% 
  clubSandwich::coef_test(vcov = "CR1", cluster = schools$cluster_code)
```

### (h)

```{r 4h}
schools %$% 
  lm(test_scores ~ treatment + age + girl + sheep + duration_village + 
       farmer + education_head + number_ppl_hh + distance_nearest_school, .) %>%
  clubSandwich::coef_test(vcov = "CR1", cluster = schools$cluster_code)
```

### (i)

```{r 4i}
sum(!is.na(schools$formal_school))
sum(!is.na(schools$test_scores))

schools %>% 
  select(formal_school, test_scores) %>% 
  psych::describe()
```

### (j)

```{r 4j}
schools %>%  
  lm(f07_test_observed ~ treatment, .) %>% 
  clubSandwich::coef_test(vcov = "CR1", cluster = schools$cluster_code)
```

